# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('head_ru', models.CharField(max_length=200, null=True)),
                ('head_en', models.CharField(max_length=200, null=True)),
                ('head_kz', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_ru', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_kz', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('link_ru', models.URLField(null=True)),
                ('link_en', models.URLField(null=True)),
                ('link_kz', models.URLField(null=True)),
                ('category_id', models.IntegerField(choices=[(1, 'Фондовый рынок статус PRO')])),
                ('idx', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kase_video',
                'ordering': ['idx', 'pk'],
            },
        ),
    ]
